[package]
name = "y2logs_model"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
nom = "7.1.1"
regex = "1.6.0"
thiserror = "1.0.35"
